#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# GL2GH Post-Migration Validation
# - Reads repos_with_status.csv generated by migration stage
# - Validates only MigrationStatus=Success rows
# - Uses GitLab API for source branch/commit/SHA
# - Uses GitHub API for target branch/commit/SHA
# - Uses ADO2GH-style branch validation threshold logic
# ============================================================

# -------------------------
# Config / env
# -------------------------
# BASE_SCRIPT_LOC="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# LOG_DIR="$BASE_SCRIPT_LOC/logs"
# ARTIFACTS_DIR="$BASE_SCRIPT_LOC/output_files"

RUN_TS="$(date +"%Y%m%d_%H%M%S")"
LOG_DIR="$PWD/logs/3_post_migration_validation"
POST_MIGRATION_VALIDATION_LOG="${POST_MIGRATION_VALIDATION_LOG:-$LOG_DIR/post-migration-validation}"

ARTIFACTS_DIR="$PWD/output_files"
REPOS_STATUS_FILE="${REPOS_STATUS_FILE:-$ARTIFACTS_DIR/migration/repos_with_status.csv}"
OUTPUT_DIR="$ARTIFACTS_DIR/post_migration_validation"

BRANCH_VALIDATION_THRESHOLD="${BRANCH_VALIDATION_THRESHOLD:-10}"
COMMIT_CHECK="${COMMIT_CHECK:-true}"

# OUTPUT_DIR="$ARTIFACTS_DIR/post-migration-validation"
LOG_FILE="${POST_MIGRATION_VALIDATION_LOG}-${RUN_TS}.log"
SUMMARY_CSV="${OUTPUT_DIR}/validation-summary_${RUN_TS}.csv"
SUMMARY_MD="${OUTPUT_DIR}/validation-summary_${RUN_TS}.md"

mkdir -p "$LOG_DIR" "$OUTPUT_DIR"

# Save all stdout+stderr to logfile AND still show on terminal
exec > >(tee -a "$LOG_FILE") 2>&1

# -------------------------
# Helpers
# -------------------------
write_log() {
  local message="$1"
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $message"
}

is_json() {
  jq -e . >/dev/null 2>&1
}

urlencode() {
  jq -rn --arg s "$1" '$s|@uri'
}

clean_field() {
  local s="${1:-}"
  s="${s%$'\r'}"
  s="${s#\"}"
  s="${s%\"}"
  s="$(printf '%s' "$s" | xargs)"
  printf '%s' "$s"
}

array_contains() {
  local seeking="$1"
  shift
  local item

  for item in "$@"; do
    [[ "$item" == "$seeking" ]] && return 0
  done

  return 1
}

parse_csv_line() {
  local line="$1"
  local -a fields=()
  local field=""
  local in_quotes=false
  local i
  local char
  local next

  for ((i=0; i<${#line}; i++)); do
    char="${line:$i:1}"
    next="${line:$((i+1)):1}"

    if [[ "$char" == '"' ]]; then
      if [[ "$in_quotes" == true ]]; then
        if [[ "$next" == '"' ]]; then
          field+='"'
          ((i++))
        else
          in_quotes=false
        fi
      else
        in_quotes=true
      fi
    elif [[ "$char" == "," && "$in_quotes" == false ]]; then
      fields+=("$field")
      field=""
    else
      field+="$char"
    fi
  done

  fields+=("$field")
  printf '%s\n' "${fields[@]}"
}

find_col() {
  local name="$1"
  local i

  for i in "${!cols[@]}"; do
    if [[ "$(clean_field "${cols[$i]}")" == "$name" ]]; then
      echo "$i"
      return 0
    fi
  done

  return 1
}

# -------------------------
# Pre-flight checks
# -------------------------
command -v gh >/dev/null 2>&1 || { echo "ERROR: GitHub CLI (gh) not found" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "ERROR: jq not found" >&2; exit 1; }
command -v curl >/dev/null 2>&1 || { echo "ERROR: curl not found" >&2; exit 1; }
command -v column >/dev/null 2>&1 || { echo "ERROR: column not found" >&2; exit 1; }

GITLAB_SERVER_URL="${GITLAB_SERVER_URL:-https://gitlab.com}"
GITLAB_SERVER_URL="${GITLAB_SERVER_URL%/}"

if [[ "$GITLAB_SERVER_URL" != http://* && "$GITLAB_SERVER_URL" != https://* ]]; then
  GITLAB_SERVER_URL="https://${GITLAB_SERVER_URL}"
fi

[[ -n "${GITLAB_PAT:-}" ]] || { echo "ERROR: GITLAB_PAT is not set" >&2; exit 1; }

if [[ -z "${GH_TOKEN:-}" && -n "${GH_PAT:-}" ]]; then
  export GH_TOKEN="${GH_PAT}"
fi

if [[ -z "${GH_TOKEN:-}" && -z "${GITHUB_TOKEN:-}" ]]; then
  if ! gh auth status >/dev/null 2>&1; then
    echo "ERROR: GitHub CLI not authenticated." >&2
    echo "       Set GH_TOKEN or GH_PAT, or run: gh auth login" >&2
    exit 1
  fi
fi

if ! gh api -X GET /user >/dev/null 2>&1; then
  echo "ERROR: GitHub auth check failed. Verify GH_TOKEN/GH_PAT scopes and SSO authorization." >&2
  exit 1
fi

if [[ ! -f "$REPOS_STATUS_FILE" ]]; then
  echo "ERROR: Migration status file not found: $REPOS_STATUS_FILE" >&2
  exit 1
fi

write_log "[INFO] Starting GitLab -> GitHub post-migration validation"
write_log "[INFO] Repos status file : $REPOS_STATUS_FILE"
write_log "[INFO] Source GitLab URL : $GITLAB_SERVER_URL"
write_log "[INFO] Output Dir        : $OUTPUT_DIR"
write_log "[INFO] Log File          : $LOG_FILE"
write_log "[INFO] Summary CSV       : $SUMMARY_CSV"
write_log "[INFO] Summary MD        : $SUMMARY_MD"

# -------------------------
# Validate repos_with_status.csv headers
# -------------------------
header="$(head -n 1 "$REPOS_STATUS_FILE" | tr -d $'\r')"
readarray -t cols < <(parse_csv_line "$header")

array_of_err_messages=()

GL_GROUP_IDX="$(find_col "gitlab_group")" || array_of_err_messages+=("[ERROR] Missing required header: gitlab_group")
GL_PROJECT_IDX="$(find_col "gitlab_project")" || array_of_err_messages+=("[ERROR] Missing required header: gitlab_project")
GH_ORG_IDX="$(find_col "github_org")" || array_of_err_messages+=("[ERROR] Missing required header: github_org")
GH_REPO_IDX="$(find_col "github_repo")" || array_of_err_messages+=("[ERROR] Missing required header: github_repo")
STATUS_IDX="$(find_col "MigrationStatus")" || array_of_err_messages+=("[ERROR] Missing required header: MigrationStatus")

if ((${#array_of_err_messages[@]})); then
  printf '%s\n' "${array_of_err_messages[@]}" >&2
  echo "[ERROR] Header must contain: gitlab_group, gitlab_project, github_org, github_repo, MigrationStatus" >&2
  exit 1
fi

# -------------------------
# GitLab API helpers
# -------------------------
gitlab_project_id() {
  local gitlab_group="$1"
  local gitlab_project="$2"

  urlencode "${gitlab_group}/${gitlab_project}"
}

gitlab_api() {
  local endpoint="$1"

  curl -sS \
    -H "PRIVATE-TOKEN: ${GITLAB_PAT}" \
    "${GITLAB_SERVER_URL}/api/v4${endpoint}"
}

gitlab_default_branch() {
  local gitlab_group="$1"
  local gitlab_project="$2"
  local project_id
  local response

  project_id="$(gitlab_project_id "$gitlab_group" "$gitlab_project")"
  response="$(gitlab_api "/projects/${project_id}")"

  if ! echo "$response" | is_json; then
    echo ""
    return 1
  fi

  echo "$response" | jq -r '.default_branch // empty'
}

gitlab_branches() {
  local gitlab_group="$1"
  local gitlab_project="$2"
  local project_id
  local page=1
  local per_page=100
  local response
  local count

  project_id="$(gitlab_project_id "$gitlab_group" "$gitlab_project")"

  while true; do
    response="$(gitlab_api "/projects/${project_id}/repository/branches?per_page=${per_page}&page=${page}")"

    if ! echo "$response" | is_json; then
      return 1
    fi

    count="$(echo "$response" | jq 'length')"
    echo "$response" | jq -r '.[].name'

    if [[ "$count" -lt "$per_page" ]]; then
      break
    fi

    page=$((page + 1))
  done
}

gitlab_commit_count() {
  local gitlab_group="$1"
  local gitlab_project="$2"
  local branch="$3"
  local project_id
  local branch_q
  local page=1
  local per_page=100
  local total=0
  local response
  local count

  project_id="$(gitlab_project_id "$gitlab_group" "$gitlab_project")"
  branch_q="$(urlencode "$branch")"

  while true; do
    response="$(gitlab_api "/projects/${project_id}/repository/commits?ref_name=${branch_q}&per_page=${per_page}&page=${page}")"

    if ! echo "$response" | is_json; then
      write_log "❌ ERROR: GitLab commits response is not JSON for ${gitlab_group}/${gitlab_project}, branch '${branch}', page ${page}"
      return 1
    fi

    count="$(echo "$response" | jq 'length')"
    total=$((total + count))

    if [[ "$count" -lt "$per_page" ]]; then
      break
    fi

    page=$((page + 1))
  done

  echo "$total"
}

gitlab_latest_sha() {
  local gitlab_group="$1"
  local gitlab_project="$2"
  local branch="$3"
  local project_id
  local branch_q
  local response

  project_id="$(gitlab_project_id "$gitlab_group" "$gitlab_project")"
  branch_q="$(urlencode "$branch")"

  response="$(gitlab_api "/projects/${project_id}/repository/commits?ref_name=${branch_q}&per_page=1")"

  if ! echo "$response" | is_json; then
    return 1
  fi

  echo "$response" | jq -r '.[0].id // empty'
}

# -------------------------
# GitHub API helpers
# -------------------------
gh_commit_count() {
  local github_org="$1"
  local github_repo="$2"
  local branch="$3"
  local branch_q
  local page=1
  local per_page=100
  local total=0
  local response
  local count

  branch_q="$(urlencode "$branch")"

  while true; do
    response="$(gh api "/repos/$github_org/$github_repo/commits?sha=$branch_q&per_page=$per_page&page=$page" 2>/dev/null || true)"

    if ! echo "$response" | is_json; then
      write_log "❌ ERROR: GitHub commits response is not JSON for ${github_org}/${github_repo}, branch '${branch}', page ${page}"
      return 1
    fi

    count="$(echo "$response" | jq 'length')"
    total=$((total + count))

    if [[ "$count" -lt "$per_page" ]]; then
      break
    fi

    page=$((page + 1))
  done

  echo "$total"
}

gh_latest_sha() {
  local github_org="$1"
  local github_repo="$2"
  local branch="$3"
  local branch_q

  branch_q="$(urlencode "$branch")"

  gh api "/repos/$github_org/$github_repo/commits?sha=$branch_q&per_page=1" \
    --jq '.[0].sha // empty'
}

# -------------------------
# Output header
# -------------------------
printf 'github_org,github_repo,gitlab_group,gitlab_project,github_repo_exists,exists_status,github_branch_count,gitlab_branch_count,branch_count_match,github_default_branch,gitlab_default_branch,default_branch_match,branches_validated,commit_count_match,latest_sha_match,notes\n' > "$SUMMARY_CSV"

# -------------------------
# Validation function
# -------------------------
validate_migration() {
  local gitlab_group="$1"
  local gitlab_project="$2"
  local github_org="$3"
  local github_repo="$4"

  local has_validation_errors=0
  local notes=""
  local exists_status="❌"
  local github_repo_exists=false

  write_log "============================================================"
  write_log "Validating: ${gitlab_project} -> ${github_org}/${github_repo}"

  # GitHub repository existence
  if gh api -X GET "/repos/${github_org}/${github_repo}" >/dev/null 2>&1; then
    github_repo_exists=true
    exists_status="✅"
  else
    notes="GitHub repository not found or no access"
    has_validation_errors=1
  fi

  local -a gh_branch_array=()
  local -a gl_branch_array=()
  local gh_default_branch=""
  local gl_default_branch=""

  if [[ "$github_repo_exists" == true ]]; then
    if ! mapfile -t gh_branch_array < <(
      gh api "/repos/$github_org/$github_repo/branches?per_page=100" --paginate 2>/dev/null | jq -r '.[].name'
    ); then
      write_log "❌ ERROR: Failed to fetch GitHub branches for $github_org/$github_repo"
      return 1
    fi

    if ! gh_default_branch="$(gh api "/repos/$github_org/$github_repo" --jq '.default_branch // empty' 2>/dev/null)"; then
      write_log "❌ ERROR: Failed to fetch GitHub default branch for $github_org/$github_repo"
      return 1
    fi
  fi

  if ! mapfile -t gl_branch_array < <(gitlab_branches "$gitlab_group" "$gitlab_project"); then
    write_log "❌ ERROR: Failed to fetch GitLab branches for $gitlab_group/$gitlab_project"
    return 1
  fi

  if ! gl_default_branch="$(gitlab_default_branch "$gitlab_group" "$gitlab_project")"; then
    write_log "❌ ERROR: Failed to fetch GitLab default branch for $gitlab_group/$gitlab_project"
    return 1
  fi

  local gh_branch_count=${#gh_branch_array[@]}
  local gl_branch_count=${#gl_branch_array[@]}
  local branch_count_match="❌"
  local default_branch_match="❌"

  if [[ "$gh_branch_count" -eq "$gl_branch_count" ]]; then
    branch_count_match="✅"
  else
    has_validation_errors=1
  fi

  if [[ -n "$gh_default_branch" && "$gh_default_branch" == "$gl_default_branch" ]]; then
    default_branch_match="✅"
  else
    has_validation_errors=1
    notes="${notes:+$notes; }Default branch mismatch"
  fi

  write_log "Branch Count: GitLab=$gl_branch_count | GitHub=$gh_branch_count | $branch_count_match"
  write_log "Default Branch: GitLab=${gl_default_branch:-'(none)'} | GitHub=${gh_default_branch:-'(none)'} | $default_branch_match"

  # Branch name comparison
  local -a missing_in_gh=()
  local -a missing_in_gl=()
  local gl_branch
  local gh_branch

  for gl_branch in "${gl_branch_array[@]}"; do
    if ! array_contains "$gl_branch" "${gh_branch_array[@]}"; then
      missing_in_gh+=("$gl_branch")
      has_validation_errors=1
    fi
  done

  for gh_branch in "${gh_branch_array[@]}"; do
    if ! array_contains "$gh_branch" "${gl_branch_array[@]}"; then
      missing_in_gl+=("$gh_branch")
      has_validation_errors=1
    fi
  done

  if [[ "${#missing_in_gh[@]}" -gt 0 ]]; then
    write_log "Branches missing in GitHub: ${missing_in_gh[*]}"
    notes="${notes:+$notes; }Branches missing in GitHub: ${missing_in_gh[*]}"
  fi

  if [[ "${#missing_in_gl[@]}" -gt 0 ]]; then
    write_log "Branches missing in GitLab: ${missing_in_gl[*]}"
    notes="${notes:+$notes; }Branches missing in GitLab: ${missing_in_gl[*]}"
  fi

  # ADO-style threshold logic
  local -a branches_to_validate=()
  local max_branch_count="$gl_branch_count"

  if (( gh_branch_count > max_branch_count )); then
    max_branch_count="$gh_branch_count"
  fi

  if (( max_branch_count > BRANCH_VALIDATION_THRESHOLD )); then
    branches_to_validate=("$gl_default_branch")

    local branch_name
    for branch_name in "${gl_branch_array[@]}"; do
      [[ "$branch_name" == "$gl_default_branch" ]] && continue

      if array_contains "$branch_name" "${gh_branch_array[@]}"; then
        branches_to_validate+=("$branch_name")
      fi

      (( ${#branches_to_validate[@]} >= BRANCH_VALIDATION_THRESHOLD )) && break
    done

    write_log "Branch count is above $BRANCH_VALIDATION_THRESHOLD. Validating default branch and up to 9 additional common branches: ${branches_to_validate[*]}"
  else
    branches_to_validate=("${gl_branch_array[@]}")
    write_log "Branch count is $BRANCH_VALIDATION_THRESHOLD or below. Validating all branches."
  fi

  local commit_count_match="✅"
  local latest_sha_match="✅"

  if [[ "$COMMIT_CHECK" == "true" ]]; then
    local branch_name

    for branch_name in "${branches_to_validate[@]}"; do
      if [[ -z "$branch_name" || "$branch_name" == "null" ]]; then
        write_log "⚠️ WARNING: Empty branch name found. Skipping commit/SHA validation."
        continue
      fi

      if ! array_contains "$branch_name" "${gh_branch_array[@]}"; then
        write_log "Branch '$branch_name': ❌ Exists in GitLab but missing in GitHub. Skipping commit/SHA validation."
        commit_count_match="❌"
        latest_sha_match="❌"
        has_validation_errors=1
        continue
      fi

      local gh_commit_count_value
      local gh_latest_sha_value
      local gl_commit_count_value
      local gl_latest_sha_value

      if ! gh_commit_count_value="$(gh_commit_count "$github_org" "$github_repo" "$branch_name")"; then
        write_log "❌ ERROR: Failed to get GitHub commit count for branch '$branch_name'"
        commit_count_match="❌"
        has_validation_errors=1
        continue
      fi

      if ! gh_latest_sha_value="$(gh_latest_sha "$github_org" "$github_repo" "$branch_name")"; then
        write_log "❌ ERROR: Failed to get GitHub latest SHA for branch '$branch_name'"
        latest_sha_match="❌"
        has_validation_errors=1
        continue
      fi

      if ! gl_commit_count_value="$(gitlab_commit_count "$gitlab_group" "$gitlab_project" "$branch_name")"; then
        write_log "❌ ERROR: Failed to get GitLab commit count for branch '$branch_name'"
        commit_count_match="❌"
        has_validation_errors=1
        continue
      fi

      if ! gl_latest_sha_value="$(gitlab_latest_sha "$gitlab_group" "$gitlab_project" "$branch_name")"; then
        write_log "❌ ERROR: Failed to get GitLab latest SHA for branch '$branch_name'"
        latest_sha_match="❌"
        has_validation_errors=1
        continue
      fi

      local commit_count_status="❌"
      local sha_status="❌"

      if [[ "$gh_commit_count_value" -eq "$gl_commit_count_value" ]]; then
        commit_count_status="✅"
      else
        commit_count_match="❌"
        has_validation_errors=1
      fi

      if [[ -n "$gh_latest_sha_value" && -n "$gl_latest_sha_value" && "$gh_latest_sha_value" == "$gl_latest_sha_value" ]]; then
        sha_status="✅"
      else
        latest_sha_match="❌"
        has_validation_errors=1
      fi

      write_log "Branch '$branch_name': Commits=$commit_count_status | GitLab=$gl_commit_count_value | GitHub=$gh_commit_count_value"
      write_log "Branch '$branch_name': SHA=$sha_status | GitLab=$gl_latest_sha_value | GitHub=$gh_latest_sha_value"
    done
  else
    write_log "COMMIT_CHECK=false. Skipping commit count and SHA validation."
    commit_count_match="⚠️"
    latest_sha_match="⚠️"
  fi

  printf '%s\n' \
    "${github_org},${github_repo},${gitlab_group},${gitlab_project},${github_repo_exists},${exists_status},${gh_branch_count},${gl_branch_count},${branch_count_match},${gh_default_branch},${gl_default_branch},${default_branch_match},${#branches_to_validate[@]},${commit_count_match},${latest_sha_match},${notes}" \
    >> "$SUMMARY_CSV"

  if [[ "$has_validation_errors" -eq 0 ]]; then
    write_log "✅ Validation Passed"
  else
    write_log "❌ Validation Failed"
  fi

  return "$has_validation_errors"
}

# -------------------------
# Main
# -------------------------
total=0
skipped=0
ok=0
fail=0

while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line%$'\r'}"
  [[ -z "$line" ]] && continue

  total=$((total + 1))

  readarray -t fields < <(parse_csv_line "$line")

  gitlab_group="$(clean_field "${fields[$GL_GROUP_IDX]:-}")"
  gitlab_project="$(clean_field "${fields[$GL_PROJECT_IDX]:-}")"
  github_org="$(clean_field "${fields[$GH_ORG_IDX]:-}")"
  github_repo="$(clean_field "${fields[$GH_REPO_IDX]:-}")"
  status="$(clean_field "${fields[$STATUS_IDX]:-}")"

  if [[ "$status" != "Success" ]]; then
    write_log "Skipping $github_org/$github_repo because MigrationStatus=$status"
    skipped=$((skipped + 1))
    continue
  fi

  if [[ -z "$gitlab_group" || -z "$gitlab_project" || -z "$github_org" || -z "$github_repo" ]]; then
    write_log "⚠️ WARNING: Skipping invalid or incomplete row: $line"
    skipped=$((skipped + 1))
    continue
  fi

  if validate_migration "$gitlab_group" "$gitlab_project" "$github_org" "$github_repo"; then
    ok=$((ok + 1))
  else
    fail=$((fail + 1))
  fi

done < <(tail -n +2 "$REPOS_STATUS_FILE")

write_log "[INFO] Validation completed."
write_log "[INFO] Artifacts: $LOG_FILE, $SUMMARY_CSV"

# -------------------------
# Markdown summary
# -------------------------
{
  echo "# Post-Migration Validation Summary"
  echo
  echo "| GitHub Repo | GitLab Project | Exists | GH Branches | GL Branches | Branch Match | GH Default | GL Default | Default Match | Branches Validated | Commit Match | SHA Match | Notes |"
  echo "|---|---|---|---:|---:|---|---|---|---|---:|---|---|---|"

  tail -n +2 "$SUMMARY_CSV" | while IFS=',' read -r org repo gl_group gl_project repo_exists exists_status gh_bc gl_bc bc_match gh_def gl_def def_match branches_validated commit_match sha_match notes; do
    github_repo_fmt="${org}/${repo}"
    gitlab_proj_fmt="${gl_group}/${gl_project}"
    notes_esc="${notes//|/\\|}"

    echo "| ${github_repo_fmt} | ${gitlab_proj_fmt} | ${exists_status} | ${gh_bc} | ${gl_bc} | ${bc_match} | ${gh_def} | ${gl_def} | ${def_match} | ${branches_validated} | ${commit_match} | ${sha_match} | ${notes_esc} |"
  done
} > "$SUMMARY_MD"

write_log "[INFO] Markdown summary written: $SUMMARY_MD"

echo
echo "Summary:"
echo "  Total   : $total"
echo "  Skipped : $skipped"
echo "  Success : $ok"
echo "  Failed  : $fail"
echo ""
echo "Validation CSV : $SUMMARY_CSV"
echo "Validation MD  : $SUMMARY_MD"
echo "Detailed logs written to $LOG_FILE"
echo

echo "===================== FINAL SUMMARY ====================="
{
  echo "GitHub Repo|GitLab Project|Exists|Branches|Default Match|Commit Match|SHA Match"

  tail -n +2 "$SUMMARY_CSV" | while IFS=',' read -r \
      org repo gl_group gl_project repo_exists exists_status \
      gh_bc gl_bc bc_match \
      gh_def gl_def def_match \
      branches_validated commit_match sha_match notes
  do
      github_repo_fmt="${org}/${repo}"
      gitlab_proj_fmt="${gl_group}/${gl_project}"

      [[ ${#github_repo_fmt} -gt 45 ]] && github_repo_fmt="${github_repo_fmt:0:42}..."
      [[ ${#gitlab_proj_fmt} -gt 40 ]] && gitlab_proj_fmt="${gitlab_proj_fmt:0:37}..."

      printf "%s|%s|%s|%s/%s|%s|%s|%s\n" \
          "$github_repo_fmt" \
          "$gitlab_proj_fmt" \
          "$exists_status" \
          "$gh_bc" \
          "$gl_bc" \
          "$def_match" \
          "$commit_match" \
          "$sha_match"
  done
} | column -t -s '|'

echo "========================================================="

############################################
# 3-way exit code
############################################
if (( ok > 0 && fail == 0 )); then
  echo "[SUCCESS] All validated repositories passed post-migration validation"
  exit 0

elif (( ok == 0 )); then
  echo "[ERROR] No repositories passed post-migration validation"
  exit 1

else
  echo "[WARNING] Post-migration validation completed with partial success: ${ok} passed, ${fail} failed"
  exit 0
fi
